import './styles/globals.scss'
import styles from './styles/modules/RootLayout.module.scss'
import Header from '@/components/organisms/Header/Header'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${styles.layout} ${inter.className}`}>
        <Header />
        {children}
      
      </body>
    </html>
  )
}
